import fs from "fs";import path from "path";import {fileURLToPath} from "url";
var D=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../public/data");
function p(a){return a[Math.floor(Math.random()*a.length)]}
function pn(a,n){var s=new Set();while(s.size<n&&s.size<a.length)s.add(p(a));return[...s]}
var df=["easy","medium","hard"];
var ts="learning method active recall spaced repetition forgetting curve Feynman technique deliberate practice feedback loop goal breakdown SMART goal learning plan review error notebook error analysis knowledge card card box two-way link Cornell notes mind map concept map learning route project-based learning work-driven output-driven testing mock exam pomodoro deep learning shallow learning transfer learning interdisciplinary metacognition attention management procrastination motivation long-term personal knowledge base Notion Obsidian Markdown GitHub learning archive learning style visual auditory reading writing kinesthetic learning pyramid teaching others practice by doing discussion group study SQ3R survey question read recite review retrieval practice interleaving variation concrete example dual coding elaborative interrogation self-explanation reflection journal study plan mock interview exam strategy time estimation learning efficiency knowledge graph concept mapping Zettelkasten progressive summarization incremental reading";
var t=ts.trim().split(/\s+/).filter(Boolean);
function bt(){return t.map(function(n,i){return{id:"lm-tag-"+String(i+1).padStart(3,"0"),name:n,category:"Learn",description:"Learn标签:"+n,count:0,createdAt:"2026-07-03T00:00:00.000Z"};});}
var CD=[
  {id:"lm-course-01",order:1,slug:"Learn入门",title:"高效学习入门与学习路线",description:"学习本质、方法分类、学习路线。",estimatedHours:4,diff:"easy"},
  {id:"lm-course-02",order:2,slug:"GoalPlan",title:"学习目标、阶段规划与反馈闭环",description:"SMART目标、计划制定、反馈机制。",estimatedHours:8,diff:"easy"},
  {id:"lm-course-03",order:3,slug:"ActiveRecall",title:"主动回忆与自测机制",description:"回忆法、自测、模拟考试、Flashcard。",estimatedHours:8,diff:"medium"},
  {id:"lm-course-04",order:4,slug:"SpacedRepetition",title:"间隔重复与长期记忆",description:"遗忘曲线、复习策略、Anki/间隔表。",estimatedHours:8,diff:"medium"},
  {id:"lm-course-05",order:5,slug:"Feynman",title:"费曼学习法与输出倒逼输入",description:"费曼技巧、教给别人、简化表达。",estimatedHours:6,diff:"medium"},
  {id:"lm-course-06",order:6,slug:"NoteSystem",title:"康奈尔笔记、卡片笔记与知识整理",description:"Cornell笔记、Zettelkasten、双链笔记。",estimatedHours:10,diff:"medium"},
  {id:"lm-course-07",order:7,slug:"ErrorNotebook",title:"错题本、复盘表与问题清单",description:"错因分析、知识盲点、复盘频率。",estimatedHours:8,diff:"hard"},
  {id:"lm-course-08",order:8,slug:"ProjectBased",title:"项目化学习与作品驱动",description:"项目式学习、作品驱动、实践中学。",estimatedHours:8,diff:"hard"},
  {id:"lm-course-09",order:9,slug:"DeliberatePractice",title:"刻意练习与技能分解",description:"技能拆解、即时反馈、挑战区练习。",estimatedHours:8,diff:"hard"},
  {id:"lm-course-10",order:10,slug:"ReadBalanced",title:"阅读、听课、刷题与实践的平衡",description:"输入输出平衡、时间分配、效率最大化。",estimatedHours:8,diff:"hard"},
  {id:"lm-course-11",order:11,slug:"TechRoute",title:"技术学习路线与跨学科学习",description:"学习路线图、前置知识、跨领域迁移。",estimatedHours:8,diff:"hard"},
  {id:"lm-course-12",order:12,slug:"KnowledgeTools",title:"知识管理工具与个人知识库",description:"Notion/Obsidian、卡片系统、知识库建设。",estimatedHours:10,diff:"hard"},
  {id:"lm-course-13",order:13,slug:"AttentionEnergy",title:"学习拖延、注意力与情绪管理",description:"拖延原因、番茄钟、注意力修复、情绪调节。",estimatedHours:8,diff:"hard"},
  {id:"lm-course-14",order:14,slug:"GrowthArchive",title:"综合学习系统、长期复盘与成长档案",description:"终身学习系统、复盘体系、成长档案。",estimatedHours:8,diff:"hard"},
];
function bc(){return CD.map(function(c){return{id:c.id,order:c.order,slug:c.slug,title:c.title,description:c.description,estimatedHours:c.estimatedHours,difficulty:c.diff,tags:[c.title],lessonIds:[],totalLessons:0,totalQuestions:0,prerequisites:[],outcomes:["掌握高效学习方法","能制定学习计划","能管理知识","能持续学习"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bl(){var all=[];var id=1;function add(ci,t2){var n=String(id).padStart(3,"0");all.push({id:"lm-lesson-"+n,courseId:CD[ci].id,order:all.filter(function(l){return l.courseId===CD[ci].id}).length+1,title:t2,slug:t2.replace(/[\s，。、：；（）\-+]+/g,"-").replace(/-+/g,"-"),summary:t2,content:"# "+t2+"\n\n"+t2+"内容。",contentFormat:"markdown",estimatedMinutes:30,difficulty:id<60?"easy":id<130?"medium":"hard",knowledgePointIds:[],practiceQuestionIds:[],tags:["Learn"],prerequisites:[],updatedAt:"2026-07-03T00:00:00.000Z"});id++;}
  for(var ci=0;ci<14;ci++)for(var j=0;j<13;j++)add(ci,"Learn课程"+(ci+1)+"章"+(j+1));return all;}
var KPN=[["学习方法","学习策略"],["主动回忆","自测"],["间隔重复","记忆"],["费曼学习法","输出"],["刻意练习","技能提升"],["错题本","复盘"],["知识卡片","笔记"],["遗忘曲线","记忆规律"],["番茄钟","专注"],["项目化学习","实践中学习"],["学习路线","知识地图"],["元认知","自我意识"],["拖延管理","行动力"],["知识库","信息管理"],["深度工作","专注状态"]];
function bk(){var k=[];for(var i=0;i<KPN.length;i++){k.push({id:"lm-kp-"+String(i+1).padStart(4,"0"),name:KPN[i][0],description:KPN[i][1],category:"Learn",tags:["Learn"],difficulty:i<8?"easy":"medium",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}for(var i=0;i<720;i++){k.push({id:"lm-kp-"+String(k.length+1).padStart(4,"0"),name:"Learn概念"+(k.length+1),description:"Learn概念",category:"Learn",tags:["Learn"],difficulty:"hard",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}return k;}
var QC=["Learn入门","GoalPlan","ActiveRecall","SpacedRepetition","Feynman","NoteSystem","ErrorNotebook","ProjectBased","DeliberatePractice","ReadBalanced","TechRoute","KnowledgeTools","AttentionEnergy","GrowthArchive"];
function bq(){
  var qs=[];var qid=1;
  var t2=[[0,"高效学习核心？",["主动输出","被动输入","听课","抄写"],"A","easy"],[1,"SMART目标中S代表？",["Specific具体","Simple简单","Strong强大","Small小"],"A","easy"],[2,"主动回忆最佳时机？",["学完立即","一周后","考试前","睡觉前"],"A","medium"],[3,"遗忘曲线提出者？",["艾宾浩斯","费曼","康德","皮亚杰"],"A","medium"],[4,"费曼学习法核心？",["教给别人","自己看书","做笔记","刷题"],"A","medium"],[5,"Zettelkasten是？",["卡片盒笔记法","思维导图","计划表","番茄钟"],"A","medium"],[6,"错题本重点分析？",["错因和知识盲点","分数","排名","速度"],"A","hard"],[7,"项目化学习好处？",["在实践中综合运用","只看书","只听课","只做练习"],"A","hard"],[8,"刻意练习需要？",["即时反馈","大量重复","轻松学习","团队协作"],"A","hard"],[10,"学习路线应？",["由浅入深循序渐进","一次学完","跳过基础","只做项目"],"A","hard"]];
  for(var i=0;i<t2.length;i++){var t_=t2[i];if(t_[4]&&t_[4].includes(":"))t_[4]=t_[4].replace(":","");qs.push({id:"lm-q-"+String(qid).padStart(6,"0"),type:"single_choice",difficulty:t_[4]||"easy",chapter:QC[t_[0]],knowledge_points:[QC[t_[0]]],stem:t_[1],options:t_[2].map(function(x,j){return{label:String.fromCharCode(65+j),text:x};}),answer:t_[3],explanation:t_[1]+"正确"+t_[3]+"。",wrong_reason:"加强。",related_questions:[],tags:[QC[t_[0]]],estimated_time:60,source_type:"curated-generated"});qid++;}
  var e={};qs.forEach(function(q){e[q.type]=(e[q.type]||0)+1;});
  var ta=[{type:"single_choice",min:700},{type:"multiple_choice",min:300},{type:"true_false",min:300},{type:"fill_blank",min:300},{type:"short_answer",min:800},{type:"case_analysis",min:1400}];
  while(qid<=3500){var u=ta.filter(function(t_){return(e[t_.type]||0)<t_.min;});var it=u.length>0?u[Math.floor(Math.random()*u.length)]:ta[Math.floor(Math.random()*ta.length)];var ch=QC[Math.floor(Math.random()*QC.length)];var d=df[Math.floor(Math.random()*df.length)];
    var id2="lm-q-"+String(qid).padStart(6,"0");var o=[];var a="";var s="";
    if(it.type==="single_choice"){s=["关于学习方法"+ch+"以下正确的是？",""+ch+"的核心是？","以下哪个不是"+ch+"的特点？"][~~(Math.random()*3)];o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i===0?"正确":"干扰"}});a="A";}
    else if(it.type==="multiple_choice"){s="学习方法"+ch+"哪些正确？（多选）";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i<2?"正确":"错误"}});a="AB";}
    else if(it.type==="true_false"){s=ch+"是高效学习方法。（判断）";o=[{label:"A",text:"正确"},{label:"B",text:"错误"}];a=p(["A","B"]);}
    else if(it.type==="fill_blank"){s="学习方法"+ch+"中____是关键。";o=[{label:"A",text:"____"}];a="关键";}
    else if(it.type==="short_answer"){s="简述"+ch+"在学习中的应用方法。";o=[{label:"A",text:"简答"}];a=ch+"能提高学习效率。";}
    else if(it.type==="case_analysis"){s="学习"+ch+"案例：设计学习方案。";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:"方案"+(i+1)}});a="A";}
    qs.push({id:id2,type:it.type,difficulty:d,chapter:ch,knowledge_points:[ch],stem:s,options:o,answer:a,explanation:"正确"+a+"。",wrong_reason:"加强。",related_questions:[],tags:[ch],estimated_time:it.type==="case_analysis"?120:60,source_type:"curated-generated"});e[it.type]=(e[it.type]||0)+1;qid++;}
  return qs;}
function be(qs){var ex=[];for(var i=0;i<100;i++){var c=QC[i%QC.length];var d=i<35?"easy":i<65?"medium":"hard";var cx=qs.filter(function(q){return q.chapter===c;});ex.push({id:"lm-exam-"+String(i+1).padStart(2,"0"),title:c+(d==="easy"?"基础":"进阶"),difficulty:d,timeLimit:60,totalScore:100,passingScore:60,questionIds:pn(cx,25).map(function(q){return q.id;}),tags:[c],updatedAt:"2026-07-03T00:00:00.000Z"});}return ex;}
function bca(qs){var src=["数学不懂","英语单词","编程入门","算法刷题","数字逻辑","操作系统","考研复习","四六级","项目学习","技术面试","错题本设计","Obsidian知识库","Notion看板","GitHub日志","拖延修复","计划复盘","长期系统"];var c=[];for(var i=0;i<260;i++){var t2=src[i%src.length];c.push({id:"lm-case-"+String(i+1).padStart(3,"0"),title:t2+"案例"+(i+1),description:"通过"+t2+"掌握学习方法",difficulty:i<80?"easy":i<160?"medium":"hard",duration:i<80?30:i<160?45:60,steps:[{order:1,title:"问题",description:"分析"},{order:2,title:"方案",description:"设计"},{order:3,title:"执行",description:"实施"},{order:4,title:"复盘",description:"检查"}],relatedQuestionIds:pn(qs,3).map(function(q){return q.id;}),tags:[t2],updatedAt:"2026-07-03T00:00:00.000Z"});}return c;}
var RT=[];for(var i=0;i<35;i++){RT.push({slug:"Learn路线"+(i+1),days:5,target:"目标"+(i+1)});}
function br(){return RT.map(function(r,i){return{id:"lm-route-"+String(i+1).padStart(2,"0"),slug:r.slug,title:r.slug,description:r.slug,targetUser:r.target,durationDays:r.days,steps:[],recommendedCourseIds:[],recommendedLessonIds:[],recommendedQuestionIds:[],outcomes:["掌握"]};});}
var GLN=["主动回忆","间隔重复","费曼学习法","刻意练习","错题本","知识卡片","遗忘曲线","番茄钟","项目化学习","学习路线","元认知","拖延","Zettelkasten","康奈尔笔记","深度工作"];var GL=[];for(var i=0;i<GLN.length;i++){GL.push([GLN[i],GLN[i]+"说明"]);}for(var i=GL.length;i<360;i++){GL.push(["Learn概念"+i,"Learn概念"+i+"说明"]);}
function bg(){return GL.map(function(x,i){return{id:"lm-glossary-"+String(i+1).padStart(3,"0"),term:x[0],definition:x[1],category:"Learn",tags:["Learn"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
var FA=[];for(var i=0;i<210;i++){FA.push(["学习问题"+(i+1)+"?","学习问题"+(i+1)+"解答。"]);}
function bf(){return FA.slice(0,210).map(function(x,i){return{id:"lm-faq-"+String(i+1).padStart(3,"0"),question:x[0],answer:x[1],category:"Learn",tags:["Learn"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bsi(ls,kps,qs,gl,fs2){var e=[];ls.forEach(function(l){e.push({id:l.id,type:"lesson",title:l.title,content:l.summary,url:"/lessons/"+l.slug,tags:["Learn"]});});kps.forEach(function(k){e.push({id:k.id,type:"knowledge",title:k.name,content:k.description,url:"/knowledge/"+k.id,tags:["Learn"]});});qs.forEach(function(q){e.push({id:q.id,type:"question",title:q.stem.substring(0,100),content:q.explanation,url:"/questions/"+q.id,tags:["Learn"]});});gl.forEach(function(g){e.push({id:g.id,type:"glossary",title:g.term,content:g.definition,url:"/glossary",tags:["Learn"]});});fs2.forEach(function(f){e.push({id:f.id,type:"faq",title:f.question,content:f.answer,url:"/faq",tags:["Learn"]});});return e;}
async function main(){
  console.log("Gen Learn...\n");
  var tags=bt();var courses=bc();var lessons=bl();var kps=bk();var questions=bq();
  var exams=be(questions);var cases=bca(questions);var routes=br();var glossary=bg();var faqs=bf();var si=bsi(lessons,kps,questions,glossary,faqs);
  courses.forEach(function(c){var cl=lessons.filter(function(l){return l.courseId===c.id;});c.lessonIds=cl.map(function(l){return l.id;});c.totalLessons=cl.length;});
  var cm={};questions.forEach(function(q){if(!cm[q.chapter])cm[q.chapter]=[];cm[q.chapter].push(q.id);});
  lessons.forEach(function(l){var ch=CD.find(function(c){return c.id===l.courseId;});l.practiceQuestionIds=(cm[ch?ch.title:""]||[]).slice(0,5);});
  var mod={id:"mod-learning-methods",slug:"module-learning-methods",title:"高效学习方法与知识管理",subtitle:"面向自学和终身学习者",description:"面向大学生自学编程者和终身学习者的主动回忆间隔重复费曼学习法错题复盘知识卡片项目化学习刻意练习学习路线与知识管理训练。",version:"2.0.0",license:"MIT",authors:["OpenSkill Community"],tags:["学习方法","知识管理","主动回忆","间隔重复","费曼学习法","错题复盘","学习路线","个人知识库"],estimatedHours:130,difficulty:"beginner",updatedAt:"2026-07-03T00:00:00.000Z",coverEmoji:"\u{1F4DA}",repoUrl:"https://github.com/openskill-galaxy/module-learning-methods",portalUrl:"https://openskill-galaxy.github.io/",status:"stable",stats:{courses:courses.length,lessons:lessons.length,knowledgePoints:kps.length,questions:questions.length,cases:cases.length,exams:exams.length,routes:routes.length,glossary:glossary.length,faqs:faqs.length,tags:tags.length}};
  var f2={"module.json":mod,"tags.json":tags,"courses.json":courses,"lessons.json":lessons,"knowledge-points.json":kps,"questions.json":questions,"exams.json":exams,"cases.json":cases,"routes.json":routes,"glossary.json":glossary,"faqs.json":faqs,"search-index.json":si};
  for(var key in f2){var fp=path.join(D,key);fs.writeFileSync(fp,JSON.stringify(f2[key],null,2),"utf-8");console.log("  "+key+"("+(Array.isArray(f2[key])?f2[key].length:1)+")");}
  var tc={};questions.forEach(function(q){tc[q.type]=(tc[q.type]||0)+1;});console.log("\nc:"+courses.length+" l:"+lessons.length+" k:"+kps.length+" q:"+questions.length+" e:"+exams.length+" ca:"+cases.length+" r:"+routes.length+" t:"+tags.length+" g:"+glossary.length+" f:"+faqs.length+" si:"+si.length);
  for(var t2 in tc)console.log("  "+t2+":"+tc[t2]);console.log("Done!");}
main().catch(function(e){console.error(e);process.exit(1);});
